C:\Users\Alex\GitHub\Customer-Distance-Test>cd c:\Users\Alex\GitHub\Customer-Distance-Test && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\Alex\AppData\Local\Programs\Python\Python37-32\python.exe c:\Users\Alex\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 55530 c:\Users\Alex\GitHub\Customer-Distance-Test\Implementation\TestCoordinate.py "
F
======================================================================
FAIL: test_to_radians (__main__.TestCoordinate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Alex\GitHub\Customer-Distance-Test\Implementation\TestCoordinate.py", line 13, in test_to_radians
    self.assertEqual(-0.13358556363, testCoord.lon)
AssertionError: -0.13358556363 != -0.13358556363217627

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (failures=1)